### ISSUE TITLE
Any plans to update to version 6.1.1

### ISSUE THREAD

**Issue by marufbd** [yufeih/Xamarin.Smaato#2]
I could not get nativead to work

**Comment by yufeih** [comment]
Could you help with a PR?

**Comment by marufbd** [comment]
I have one working without the NativeAd, Banner ads including Custom Mediation works, want me to push that?

**Comment by yufeih** [comment]
Sure. I haven't used NativeAd, but keeping the library up to date is always a good addition

**Comment by yufeih** [comment]
https://github.com/yufeih/Xamarin.Smaato/pull/3
